name: CI/CD Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run tests
      run: dotnet test --no-build --verbosity normal
    - name: Generate coverage report
      run: dotnet test --collect:"XPlat Code Coverage"
    - name: Publish test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/coverage.cobertura.xml'
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/master' && success()
    steps:
    - name: Deploy
      run: dotnet publish -c Release -o ./deploy
